### PR TITLE
add Transaction & Report

### PR DESCRIPTION
**Pull request by David-Kurniawan**

### CODE REVIEW

**Comment by David-Kurniawan** [comment]
Hold on, I'm also adding report API

**Comment by David-Kurniawan** [comment]
All Done.

Hopefully you can review ASAP 😃

**Comment by xen-HendryZheng** [comment]
Hi @David-Kurniawan 
Thank you for your interest in Xendit-PHP SDK.

Do you mind updating composer lock file?
The checks are failing because of Composer lock md5 file is not aligned with composer json.

Attached below:
image

**Comment by David-Kurniawan** [comment]
Hi @xen-HendryZheng 
Uhm... already double check here https://github.com/xendit/xendit-php/pull/144/files

No, iam not working in composer lock


maybe from here: https://github.com/xendit/xendit-php/commit/cb7078912113706b5e42d2dfc5d8ecfe2bf94e98

**Comment by David-Kurniawan** [comment]
@xen-HendryZheng any update regarding this PR?

**Comment by xen-HendryZheng** [comment]
> @xen-HendryZheng any update regarding this PR?

Hi @David-Kurniawan We are currently going to release this [PR](https://github.com/xendit/xendit-php/pull/145) to resolve the composer lock md5 issue. Once this release, you may update your branch and , we'll review your PR ya.

Thanks for contributing to this SDk.

**Comment by xen-HendryZheng** [comment]
Hi @David-Kurniawan 
Can you merge [this](https://github.com/xendit/xendit-php/pull/145) back to your PR and we shall begin the PR review process.

**Comment by David-Kurniawan** [comment]
hi @xen-HendryZheng 
Updated ya

**Review by xen-HendryZheng — APPROVED** [review]
Reviewed all good. Merging Transaction & Report

**Pull request merged**
