### PR TITLE
Http timeout

### PR DESCRIPTION
**Pull request by Nick233333**

### CODE REVIEW

**Comment by stanleynguyen** [comment]
Hey @Nick233333. Thanks for the suggestion. 
I would suggest we do a `setHttpClient` to enable swapping out the whole default client instead of just timeout parameter. Would you be able to do so? 
We have that in the roadmap but I can't promise you on an exact date yet.

**Comment by Nick233333** [comment]
@stanleynguyen 

```
Xendit::setApiKey($config['secret_api_key']);
$http = new GuzzleHttp\Client([
     'base_uri' => strval(Xendit::$apiBase),
    'verify' => false,
    'timeout' => 60
]);
\Xendit\ApiRequestor::setHttpClient($http);
```
not work!

**Comment by stanleynguyen** [comment]
@Nick233333 looks like that because it's using the default ApiRequester here 
https://github.com/xendit/xendit-php/blob/93f66476fa073f3be3325aa9e8511992aa0b9788/src/ApiOperations/Request.php#L75
no matter what. We will need to fix this bug

**Comment by Nick233333** [comment]
@stanleynguyen 
😅When can I fix it, can I merge my request first?

**Comment by stanleynguyen** [comment]
@Nick233333 for now I will default the timeOut to 60 without extending the package interface with `setTimeout` method. Is that okay? I can make the patch soon.

**Comment by Nick233333** [comment]
@stanleynguyen ok ! thanks

**Comment by stanleynguyen** [comment]
Closed in favor of temporary patch https://github.com/xendit/xendit-php/pull/69

**Comment by stanleynguyen** [comment]
Hey @Nick233333, the patch [2.3.1](https://packagist.org/packages/xendit/xendit-php#2.3.1) has been released. Please let me know if that works for you

**Pull request closed without merging**
